"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CircleAlert, CircleCheck, FileSpreadsheet, GitCompareArrows, Info, Upload } from "lucide-react";
import { makeDemoWorkspace } from "@/lib/showcase-data";
import { DemoDataNotice, PanelTitle, ToneTag } from "@/components/showcase-ui";

const workbookChanges = [
  { id: "change-01", title: "Neela Mazhai", field: "Language", before: "Tamil", after: "Tamil", kind: "Unchanged", note: "Matching record" },
  { id: "change-02", title: "Vaanam Thodum", field: "Singer", before: "Nila Prakash", after: "Nila Prakash & Arjun Dev", kind: "Changed", note: "Check performer credit" },
  { id: "change-03", title: "Pudhu Paadhai", field: "Rights owner", before: "Veedu Audio Works", after: "Veedu Audio Works / New Leaf Publishing", kind: "Conflict", note: "Review the underlying composition split" },
  { id: "change-04", title: "First Light", field: "ISRC", before: "Not provided", after: "IN-ABC-26-001", kind: "Added", note: "New identifier supplied" },
  { id: "change-05", title: "Oru Naal", field: "Territory", before: "United Kingdom", after: "India; United Kingdom", kind: "Conflict", note: "Confirm the scope against the signed record" },
];

const songVersions: Record<string, { title: string; film: string; versions: { id: string; name: string; detail: string; master: string; composition: string; updated: string }[] }> = {
  "song-vaanam": { title: "Vaanam Thodum", film: "Neela Mazhai", versions: [
    { id: "ver-original", name: "Original recording", detail: "Vocal · 4:12 · ISRC IN-ABC-22-101", master: "India record reviewed; end date shown in rights ledger", composition: "Publisher split needs confirmation", updated: "Updated Sep 30" },
    { id: "ver-instrumental", name: "Instrumental", detail: "No lead vocal · 4:10 · ISRC IN-ABC-22-102", master: "Separate master record; owner confirmation pending", composition: "Same composition; scope needs review", updated: "Updated Sep 28" },
    { id: "ver-clean", name: "Clean edit", detail: "Broadcast edit · 3:46 · ISRC IN-ABC-22-103", master: "Clean master reference recorded", composition: "Composition terms not checked for this edit", updated: "Updated Sep 21" },
  ] },
  "song-maalai": { title: "Maalai Neram", film: "Neela Mazhai", versions: [
    { id: "ver-maalai-original", name: "Original recording", detail: "Vocal · 3:58 · ISRC IN-ABC-22-104", master: "India rights record on file", composition: "Publishing details require review", updated: "Updated Sep 29" },
    { id: "ver-maalai-acoustic", name: "Acoustic version", detail: "Alternate arrangement · 3:31 · ISRC pending", master: "Master ownership not confirmed", composition: "Composition link recorded; verify the grant", updated: "Updated Sep 18" },
  ] },
};

export function CatalogueSetupPage() {
  const [tab, setTab] = useState("Compare updates");
  const [approved, setApproved] = useState<string[]>([]);
  const workspace = makeDemoWorkspace();
  const unresolved = workbookChanges.filter((item) => item.kind === "Conflict" && !approved.includes(item.id)).length;
  const accept = (id: string) => setApproved((items) => items.includes(id) ? items : [...items, id]);

  return <div className="showcase-stack"><DemoDataNotice>Workbook migration preview · sample changes are not written into the catalogue.</DemoDataNotice><div className="showcase-tabs" role="tablist" aria-label="Catalogue setup views">{["Column mapping", "Compare updates", "Data quality"].map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    <section className="showcase-panel migration-file-card"><div className="migration-file-icon"><FileSpreadsheet size={18} /></div><div><strong>Pyramid_Q4_Catalogue_Update.xlsx</strong><small>Received Sep 30 · 3 sheets · sample workbook</small></div><div className="migration-file-stats"><span><b>4</b> new rows</span><span><b>7</b> changed fields</span><span className={unresolved ? "warning" : "good"}><b>{unresolved}</b> conflicts left</span></div><Link href="/catalogue" className="button secondary"><Upload size={12} />Open workbook import</Link></section>
    {tab === "Column mapping" && <section className="showcase-panel"><PanelTitle title="Map workbook columns" detail="Match source headers to Pyramid fields before reviewing rows." /><div className="mapping-table"><div className="mapping-header"><span>Workbook sheet</span><span>Source column</span><span>Pyramid field</span><span>Check</span></div>{[["Films", "Film Name", "Film title", "Matched"], ["Songs", "Track Title", "Song title", "Matched"], ["Songs", "Movie", "Parent film", "Matched"], ["Songs", "Vocalist", "Singer", "Review"], ["Rights", "Usage region", "Territory", "Matched"], ["Rights", "Rights until", "Expiry date", "Needs mapping"]].map((row, index) => <div className="mapping-row" key={`${row[0]}-${row[1]}`}><span>{row[0]}</span><span>{row[1]}</span><select aria-label={`Map ${row[1]}`} defaultValue={row[2]}><option>{row[2]}</option><option>Skip this field</option><option>Unmapped</option></select><ToneTag tone={index === 5 ? "warning" : index === 3 ? "neutral" : "good"}>{row[3]}</ToneTag></div>)}</div><div className="migration-footnote"><Info size={13} /><span>Expiry is calculated from start date and license period. A workbook status column is not imported as an authoritative rights status.</span></div></section>}
    {tab === "Compare updates" && <section className="showcase-panel"><PanelTitle title="Review changes before import" detail="Approve individual updates. Conflicts stay out until the rights team resolves them." action={<ToneTag tone={unresolved ? "warning" : "good"}>{unresolved} conflicts</ToneTag>} /><div className="table-wrap"><table className="compare-table"><thead><tr><th>Record</th><th>Field</th><th>Current value</th><th>Workbook value</th><th>Change</th><th>Review</th></tr></thead><tbody>{workbookChanges.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small className="table-subtext">{item.note}</small></td><td>{item.field}</td><td>{item.before}</td><td>{item.after}</td><td><ToneTag tone={item.kind === "Conflict" ? "warning" : item.kind === "Added" ? "good" : "neutral"}>{item.kind}</ToneTag></td><td>{approved.includes(item.id) ? <ToneTag tone="good"><Check size={10} />Approved</ToneTag> : <button type="button" className="button secondary" onClick={() => accept(item.id)} disabled={item.kind === "Conflict"}><Check size={11} />{item.kind === "Conflict" ? "Resolve first" : "Approve"}</button>}</td></tr>)}</tbody></table></div><div className="migration-footnote"><CircleAlert size={13} /><span>Conflict rows require a manual review. Approving a sample row only updates this preview session.</span></div></section>}
    {tab === "Data quality" && <div className="showcase-two-col"><section className="showcase-panel"><PanelTitle title="Data-quality checks" detail="Resolve these before moving a catalogue into shared use." /><div className="quality-check-list"><article><span className="quality-icon danger"><CircleAlert size={14} /></span><div><strong>Duplicate candidates</strong><small>3 possible duplicate songs across 2 films</small><p>Same normalized title with different punctuation or spelling.</p></div><ToneTag tone="warning">Review</ToneTag></article><article><span className="quality-icon warning"><Info size={14} /></span><div><strong>Missing metadata</strong><small>12 records need a field checked</small><p>Language, singer, or year is blank in the sample workbook.</p></div><ToneTag tone="warning">12 rows</ToneTag></article><article><span className="quality-icon good"><Check size={14} /></span><div><strong>Parent-film links</strong><small>{workspace.songs.length} sample songs matched to a film</small><p>Unmatched songs are held out of the import preview.</p></div><ToneTag tone="good">Matched</ToneTag></article></div></section><section className="showcase-panel"><PanelTitle title="Migration steps" detail="A reviewable import path for a client workbook." /><ol className="migration-steps"><li><b>Map</b><span>Connect workbook columns to catalogue fields.</span></li><li><b>Match</b><span>Link songs to films and identify duplicates.</span></li><li><b>Review</b><span>Resolve conflicts and approve each changed field.</span></li><li><b>Import</b><span>Confirm the final preview before writing to the shared database.</span></li></ol><Link href="/catalogue" className="button secondary">Go to catalogue <ArrowRight size={12} /></Link></section></div>}
  </div>;
}

export function SongVersionPage({ songId }: { songId: string }) {
  const workspace = makeDemoWorkspace();
  const row = workspace.songs.find((item) => item.id === songId);
  const parent = row ? workspace.films.find((film) => film.id === row.film_id) : undefined;
  const song = songVersions[songId] ?? (row ? {
    title: String(row.title), film: String(parent?.title ?? "Film not linked"), versions: [
      { id: `${songId}-original`, name: "Original recording", detail: `${String(row.language ?? "Audio")} · sample recording · identifier not supplied`, master: "Master ownership needs confirmation against the source agreement", composition: "Composition/publishing information needs a separate review", updated: "Sample record" },
      { id: `${songId}-alternate`, name: "Alternate edit (sample)", detail: "Alternate version reference · duration and identifier pending", master: "No version-specific master grant is recorded in this preview", composition: "Do not assume the composition grant covers this edit", updated: "Sample record" },
    ],
  } : undefined);
  if (!song) return <section className="showcase-panel notification-empty"><strong>Song version group not found</strong><Link href="/catalogue" className="inline-link"><ArrowLeft size={12} />Back to catalogue</Link></section>;
  return <div className="showcase-stack"><DemoDataNotice>Version family preview · each recording and edit needs its own rights review.</DemoDataNotice><Link href="/catalogue" className="inline-link"><ArrowLeft size={12} />Back to catalogue</Link><section className="showcase-panel version-family-hero"><span className="version-family-icon"><GitCompareArrows size={18} /></span><div><p className="eyebrow">Song family · {song.film}</p><h2>{song.title}</h2><p>Compare the original and alternate recordings without assuming they share the same rights or availability.</p></div><ToneTag tone="purple">{song.versions.length} versions</ToneTag></section><section className="showcase-panel"><PanelTitle title="Linked versions" detail="Recording/master and composition/publishing notes are shown independently for each version." /><div className="version-list">{song.versions.map((version, index) => <article className="version-card" key={version.id}><div className="version-card-head"><span className="version-number">0{index + 1}</span><div><strong>{version.name}</strong><small>{version.detail}</small></div><ToneTag tone={index === 0 ? "good" : "neutral"}>{index === 0 ? "Original" : "Alternate"}</ToneTag></div><div className="version-rights-grid"><div><b><ShieldCheckIcon />Recording / master</b><p>{version.master}</p></div><div><b><ShieldCheckIcon />Composition / publishing</b><p>{version.composition}</p></div></div><small className="version-updated">{version.updated} · sample note only</small></article>)}</div></section><div className="rights-check-intro"><Info size={15} /><p>The current sample database schema links rights to films. Version-level rights are shown as a product preview and will need a schema change before they can be saved to Supabase.</p></div></div>;
}

function ShieldCheckIcon() { return <CircleCheck size={12} />; }
