"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, CalendarClock, Check, CircleAlert, CircleDollarSign, Clock3, Download, FileCheck2, FileText, HandCoins, MapPin, Search, ShieldCheck } from "lucide-react";
import { demoClients, demoDeals, demoHolds, demoRenewals, demoRequests, type DemoRequest } from "@/lib/showcase-data";
import { DemoDataNotice, InitialAvatar, MetricTiles, PanelTitle, SectionTabs, ToneTag } from "@/components/showcase-ui";

function LicensingTabs({ active }: { active: string }) {
  return <SectionTabs items={[
    { label: "Request inbox", href: "/licensing", active: active === "Requests" },
    { label: "Holds & conflicts", href: "/holds", active: active === "Holds" },
    { label: "Quotes & licenses", href: "/deals", active: active === "Deals" },
    { label: "Renewals", href: "/renewals", active: active === "Renewals" },
  ]} />;
}

export function LicensingInboxPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All requests");
  const requests = useMemo(() => demoRequests.filter((request) => {
    const matchesSearch = `${request.client} ${request.title} ${request.campaign} ${request.territory}`.toLowerCase().includes(query.toLowerCase());
    return matchesSearch && (status === "All requests" || request.status === status);
  }), [query, status]);

  return <div className="showcase-stack"><DemoDataNotice>Sample licensing workflow · requests and quotes shown here are illustrative, not customer records.</DemoDataNotice><LicensingTabs active="Requests" /><MetricTiles items={[
    { label: "Open requests", value: demoRequests.filter((item) => item.status === "Received" || item.status === "Reviewing").length, note: "Need team review", icon: <BriefcaseBusiness size={14} />, tone: "warning" },
    { label: "Shortlists in progress", value: 3, note: "Rights review underway", icon: <ShieldCheck size={14} /> },
    { label: "Quotes sent", value: demoRequests.filter((item) => item.status === "Quoted").length, note: "Awaiting buyer response", icon: <HandCoins size={14} />, tone: "good" },
    { label: "Deadlines this week", value: 2, note: "Sample request deadlines", icon: <CalendarClock size={14} />, tone: "warning" },
  ]} />
    <section className="showcase-panel"><PanelTitle title="Request inbox" detail="Track every brief from intake to quote and close." action={<Link href="/licensing/req-lotus-youtube" className="button"><BriefcaseBusiness size={13} />Open featured case</Link>} /><div className="showcase-toolbar"><div className="input-wrap"><Search size={13} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search client, brief, or territory…" /></div><select className="select" aria-label="Filter request status" value={status} onChange={(event) => setStatus(event.target.value)}>{["All requests", "Received", "Reviewing", "Quoted", "Approved"].map((item) => <option key={item}>{item}</option>)}</select><span className="showcase-toolbar-count">{requests.length} cases</span></div>
      <div className="table-wrap"><table><thead><tr><th>Request</th><th>Buyer</th><th>Territory & use</th><th>Deadline</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><Link href={`/licensing/${request.id}`} className="showcase-table-primary"><strong>{request.title}</strong><small>{request.campaign}</small></Link></td><td><Link href={`/clients/${request.clientId}`} className="crm-mini-link"><InitialAvatar name={request.client} tone="peach" />{request.client}</Link></td><td>{request.territory}<small className="table-subtext">{request.use} · {request.platform}</small></td><td>{request.deadline}</td><td>{request.owner}</td><td><ToneTag tone={request.status === "Quoted" || request.status === "Approved" ? "good" : request.status === "Reviewing" ? "warning" : "neutral"}>{request.status}</ToneTag></td><td><Link href={`/licensing/${request.id}`} className="icon-button" aria-label={`Open ${request.title}`}><ArrowRight size={14} /></Link></td></tr>)}</tbody></table>{requests.length === 0 && <div className="notification-empty"><strong>No matching requests</strong><span>Try a different search or status.</span></div>}</div>
    </section>
    <div className="showcase-two-col"><section className="showcase-panel"><PanelTitle title="How a request moves" detail="A clear path from brief to recorded deal." /><div className="licensing-step-list">{["Received", "Reviewing", "Quoted", "Approved", "Closed"].map((step, index) => <div className="licensing-step" key={step}><span className={index < 3 ? "complete" : ""}>{index < 3 ? <Check size={11} /> : index + 1}</span><div><strong>{step}</strong><small>{["Capture the brief and deadline", "Check candidates, rights, and holds", "Share pricing and a shortlist", "Confirm scope before contract", "Record outcome and learn from demand"][index]}</small></div>{index < 4 && <i />}</div>)}</div></section><section className="showcase-panel licensing-reminder"><span className="showcase-metric-icon"><CircleAlert size={15} /></span><h2>Rights review stays transparent</h2><p>Each case lists the recording and composition information on file, plus missing or unclear items for follow-up.</p><Link href="/holds" className="inline-link">Review active holds <ArrowRight size={12} /></Link></section></div>
  </div>;
}

export function LicensingRequestPage({ requestId }: { requestId: string }) {
  const request = demoRequests.find((item) => item.id === requestId);
  if (!request) return <section className="showcase-panel notification-empty"><strong>Request not found</strong><Link href="/licensing" className="inline-link"><ArrowLeft size={12} />Back to inbox</Link></section>;
  const client = demoClients.find((item) => item.id === request.clientId);
  const hold = demoHolds.find((item) => item.requestId === request.id);

  return <div className="showcase-stack"><DemoDataNotice>Request case preview · rights notes explain what the sample records show and what remains unclear.</DemoDataNotice><LicensingTabs active="Requests" /><Link href="/licensing" className="inline-link"><ArrowLeft size={12} />Back to request inbox</Link>
    <section className="showcase-panel case-hero"><div className="case-hero-top"><div><div className="case-kicker">{request.id.toUpperCase()} <span>·</span> {request.campaign}</div><h2>{request.title}</h2><p>{request.brief}</p></div><ToneTag tone={request.status === "Quoted" || request.status === "Approved" ? "good" : "warning"}>{request.status}</ToneTag></div><div className="case-facts"><span><b>Buyer</b><Link href={`/clients/${request.clientId}`}>{request.client} <ArrowRight size={11} /></Link></span><span><b>Use</b>{request.use}</span><span><b>Platform</b>{request.platform}</span><span><b>Territory</b><span><MapPin size={12} />{request.territory}</span></span><span><b>Term</b>{request.startDate} → {request.endDate}</span><span><b>Deadline</b>{request.deadline}</span><span><b>Budget range</b>{request.budget}</span><span><b>Assigned to</b>{request.owner}</span></div></section>
    <div className="case-action-row"><Link href={`/licensing/${request.id}/package`} className="button"><FileCheck2 size={13} />Preview buyer package</Link><Link href="/holds" className="button secondary"><Clock3 size={13} />Check holds & conflicts</Link><Link href="/deals" className="button secondary"><CircleDollarSign size={13} />Quotes & licenses</Link></div>
    <section className="showcase-panel"><PanelTitle title="Candidate shortlist & rights check" detail={`Search brief: ${request.requestedStyle}. Review recording and composition separately.`} /><div className="rights-check-intro"><ShieldCheck size={15} /><p>Rights summary describes records available for review. A missing or unclear record needs follow-up; this screen does not guarantee legal clearance.</p></div><div className="table-wrap"><table className="rights-check-table"><thead><tr><th>Candidate</th><th>Fit</th><th>Recording / master</th><th>Composition / publishing</th><th>Review note</th></tr></thead><tbody>{request.songs.map((song) => <tr key={song.title}><td><strong>{song.title}</strong><small className="table-subtext">{song.film}</small></td><td><ToneTag tone={song.fit === "Strong match" || song.fit === "Selected" ? "good" : "neutral"}>{song.fit}</ToneTag></td><td><span className="rights-summary-cell">{song.recording}</span></td><td><span className="rights-summary-cell">{song.composition}</span></td><td>{song.note}</td></tr>)}</tbody></table></div></section>
    <div className="showcase-two-col"><section className="showcase-panel"><PanelTitle title="Temporary hold" detail="Holds are scoped by territory, media, and end date." action={<Link href="/holds" className="inline-link">Manage holds <ArrowRight size={12} /></Link>} />{hold ? <div className="hold-detail-card"><div><strong>{hold.song}</strong><small>{hold.film}</small></div><ToneTag tone={hold.status === "Active" ? "warning" : "danger"}>{hold.status}</ToneTag><p>Held for {hold.client} · {hold.territory} · {hold.media}</p><small>Hold ends {hold.expires} · owner {hold.owner}</small></div> : <div className="panel-body muted">No hold is attached to this request yet.</div>}</section><section className="showcase-panel"><PanelTitle title="Team checklist" detail="Keep the next action visible to the whole team." /><div className="case-checklist">{["Confirm requested territory and dates", "Review recording and composition records", "Check overlapping holds", "Approve buyer-safe shortlist", "Record quote outcome"].map((item, index) => <div key={item}><span className={index < (request.status === "Quoted" || request.status === "Approved" ? 4 : 2) ? "done" : ""}>{index < (request.status === "Quoted" || request.status === "Approved" ? 4 : 2) && <Check size={11} />}</span><span>{item}</span></div>)}</div><p className="case-private-note"><strong>Internal note (not included in buyer package):</strong> {client?.notes}</p></section></div>
  </div>;
}

export function HoldsPage() {
  return <div className="showcase-stack"><DemoDataNotice>Sample holds · these entries illustrate team coordination and do not reserve real rights.</DemoDataNotice><LicensingTabs active="Holds" /><MetricTiles items={[
    { label: "Active holds", value: demoHolds.length, note: "Scoped by territory and media", icon: <Clock3 size={14} />, tone: "warning" },
    { label: "Conflict checks", value: 1, note: "Needs staff review", icon: <CircleAlert size={14} />, tone: "warning" },
    { label: "Ending this week", value: 2, note: "Follow up with request owners", icon: <CalendarClock size={14} /> },
  ]} /><section className="showcase-panel"><PanelTitle title="Holds & potential overlaps" detail="A hold coordinates active offers. It is not a legal clearance or an exclusive license." /><div className="table-wrap"><table><thead><tr><th>Song / version</th><th>Buyer & case</th><th>Territory</th><th>Media</th><th>Hold ends</th><th>Owner</th><th>Status</th></tr></thead><tbody>{demoHolds.map((hold) => <tr key={hold.id}><td><strong>{hold.song}</strong><small className="table-subtext">{hold.film}</small></td><td><Link className="showcase-table-primary" href={`/licensing/${hold.requestId}`}><strong>{hold.client}</strong><small>Open request case</small></Link></td><td>{hold.territory}</td><td>{hold.media}</td><td>{hold.expires}</td><td>{hold.owner}</td><td><ToneTag tone={hold.status === "Active" ? "warning" : "danger"}>{hold.status}</ToneTag></td></tr>)}</tbody></table></div></section><section className="hold-conflict-callout"><CircleAlert size={16} /><div><strong>Potential overlap found</strong><p>Nila Kaayum is held for a broadcast request while another team member is reviewing the same territory. Open both cases and confirm timing before sending a quote.</p></div><Link href="/licensing/req-bluepeacock-drama" className="inline-link">Review case <ArrowRight size={12} /></Link></section></div>;
}

export function DealsPage() {
  return <div className="showcase-stack"><DemoDataNotice>Sample quotes and license pipeline · amounts and stages are for product demonstration only.</DemoDataNotice><LicensingTabs active="Deals" /><MetricTiles items={[
    { label: "Quote value in review", value: "₹28.4L", note: "Illustrative pipeline", icon: <CircleDollarSign size={14} />, tone: "good" },
    { label: "Quotes awaiting reply", value: 2, note: "Follow up with buyers", icon: <FileText size={14} />, tone: "warning" },
    { label: "Approved shortlists", value: 1, note: "Confirm terms before license", icon: <BadgeCheck size={14} /> },
  ]} /><section className="showcase-panel"><PanelTitle title="Quotes & customer licenses" detail="Keep a clear link from quote to request case and eventual license." /><div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Buyer</th><th>Type</th><th>Illustrative amount</th><th>Updated</th><th>Stage</th><th></th></tr></thead><tbody>{demoDeals.map((deal) => <tr key={deal.id}><td><Link className="showcase-table-primary" href={`/licensing/${deal.requestId}`}><strong>{deal.title}</strong><small>Open request case</small></Link></td><td>{deal.client}</td><td>{deal.type}</td><td><strong>{deal.amount}</strong></td><td>{deal.updated}</td><td><ToneTag tone={deal.stage === "Quote sent" ? "good" : "warning"}>{deal.stage}</ToneTag></td><td><Link className="icon-button" href={`/licensing/${deal.requestId}`} aria-label={`Open ${deal.title}`}><ArrowRight size={14} /></Link></td></tr>)}</tbody></table></div><div className="buyer-package-footer"><div><FileCheck2 size={15} /><span><strong>Buyer package preview</strong><small>See the approved metadata and rights summary without internal notes.</small></span></div><Link className="button secondary" href="/licensing/req-lotus-youtube/package"><FileText size={13} />Open sample package</Link></div></section></div>;
}

export function RenewalsPage() {
  return <div className="showcase-stack"><DemoDataNotice>Sample renewal queue · catalogue rights expiry and customer license dates are shown as separate events.</DemoDataNotice><LicensingTabs active="Renewals" /><MetricTiles items={[
    { label: "Follow-ups due", value: demoRenewals.length, note: "Across different license events", icon: <CalendarClock size={14} />, tone: "warning" },
    { label: "Catalogue rights", value: 1, note: "Rights owner extension review", icon: <ShieldCheck size={14} /> },
    { label: "Customer options", value: 2, note: "Buyer license milestones", icon: <FileCheck2 size={14} />, tone: "good" },
  ]} /><section className="showcase-panel"><PanelTitle title="Renewal & option calendar" detail="Assign an owner and follow-up date before an option window closes." /><div className="renewal-list">{demoRenewals.map((item, index) => <article className="renewal-row" key={item.id}><div className={`renewal-date ${index === 0 ? "soon" : ""}`}><CalendarClock size={14} /><span>{item.due}</span></div><div className="renewal-main"><div><ToneTag tone={item.type === "Catalogue rights expiry" ? "purple" : "blue"}>{item.type}</ToneTag><h3>{item.song} <span>· {item.film}</span></h3><p>{item.note}</p></div><small>Buyer: {item.client}</small></div><div className="renewal-owner"><b>Owner</b><span>{item.owner}</span></div><Link href={item.id === "renew-01" ? "/rights" : `/licensing/${item.id === "renew-02" ? "req-mango-launch" : "req-lotus-youtube"}`} className="button secondary">Review <ArrowRight size={12} /></Link></article>)}</div></section><div className="rights-check-intro"><CircleAlert size={15} /><p>An expiring catalogue right affects what the rights owner can grant. An expiring customer license affects a deal already made. Keep the dates and follow-up owners distinct.</p></div></div>;
}

export function BuyerPackagePage({ requestId }: { requestId: string }) {
  const [printed, setPrinted] = useState(false);
  const request: DemoRequest | undefined = demoRequests.find((item) => item.id === requestId);
  if (!request) return <section className="showcase-panel notification-empty"><strong>Request not found</strong><Link href="/licensing" className="inline-link"><ArrowLeft size={12} />Back to inbox</Link></section>;
  const client = demoClients.find((item) => item.id === request.clientId);
  const printableSongs = request.songs.filter((song) => song.fit === "Strong match" || song.fit === "Selected");
  const printPackage = () => { setPrinted(true); window.print(); };

  return <div className="showcase-stack"><DemoDataNotice>Buyer package preview · internal notes, private contracts, and unresolved candidates are excluded.</DemoDataNotice><Link href={`/licensing/${request.id}`} className="inline-link"><ArrowLeft size={12} />Back to request case</Link><section className="package-sheet"><div className="package-brand"><span className="brand-mark">P</span><span>pyramid <small>Rights workspace</small></span><ToneTag tone="good">Buyer preview</ToneTag></div><p className="eyebrow">Music shortlist · {request.territory}</p><h2>{request.campaign}</h2><p className="package-subheading">Prepared for {client?.name ?? request.client} · {request.use} · {request.platform}</p><div className="package-term"><span><b>Requested term</b>{request.startDate} to {request.endDate}</span><span><b>Territory</b>{request.territory}</span><span><b>Prepared by</b>Pyramid Rights Team</span></div><h3>Proposed shortlist</h3>{printableSongs.length ? printableSongs.map((song, index) => <article className="package-song" key={song.title}><span className="package-song-number">0{index + 1}</span><div><strong>{song.title}</strong><small>{song.film} · {song.fit}</small><p>Preview link available on request · metadata shown for identification.</p></div><ToneTag tone="good">Proposed</ToneTag></article>) : <p>No proposed candidates are available in this sample case.</p>}<div className="package-rights-note"><ShieldCheck size={15} /><p><strong>Rights information summary</strong><br />The shortlist reflects a preliminary review of records noted in the request case. Final availability, scope, and permissions remain subject to written confirmation and agreement.</p></div><div className="package-footer"><span>Prepared for discussion · not a license or legal clearance</span><span>pyramid.example</span></div></section><div className="package-actions"><Link href={`/licensing/${request.id}`} className="button secondary"><ArrowLeft size={13} />Return to case</Link><button type="button" className="button" onClick={printPackage}><Download size={13} />{printed ? "Print again / save PDF" : "Print or save as PDF"}</button></div></div>;
}
